// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: producer_service.proto

package rabbitmq_producer

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastType int32

const (
	CastType_ACTOR           CastType = 0
	CastType_DIRECTOR        CastType = 1
	CastType_PRODUCER        CastType = 2
	CastType_WRITER          CastType = 3
	CastType_CINEMATOGRAPHER CastType = 4
	CastType_EDITOR          CastType = 5
	CastType_COMPOSER        CastType = 6
)

// Enum value maps for CastType.
var (
	CastType_name = map[int32]string{
		0: "ACTOR",
		1: "DIRECTOR",
		2: "PRODUCER",
		3: "WRITER",
		4: "CINEMATOGRAPHER",
		5: "EDITOR",
		6: "COMPOSER",
	}
	CastType_value = map[string]int32{
		"ACTOR":           0,
		"DIRECTOR":        1,
		"PRODUCER":        2,
		"WRITER":          3,
		"CINEMATOGRAPHER": 4,
		"EDITOR":          5,
		"COMPOSER":        6,
	}
)

func (x CastType) Enum() *CastType {
	p := new(CastType)
	*p = x
	return p
}

func (x CastType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastType) Descriptor() protoreflect.EnumDescriptor {
	return file_producer_service_proto_enumTypes[0].Descriptor()
}

func (CastType) Type() protoreflect.EnumType {
	return &file_producer_service_proto_enumTypes[0]
}

func (x CastType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CastType.Descriptor instead.
func (CastType) EnumDescriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0}
}

type MovieFormat int32

const (
	MovieFormat_TWO_D   MovieFormat = 0
	MovieFormat_THREE_D MovieFormat = 1
	MovieFormat_IMAX    MovieFormat = 2
	MovieFormat_FOUR_D  MovieFormat = 3
)

// Enum value maps for MovieFormat.
var (
	MovieFormat_name = map[int32]string{
		0: "TWO_D",
		1: "THREE_D",
		2: "IMAX",
		3: "FOUR_D",
	}
	MovieFormat_value = map[string]int32{
		"TWO_D":   0,
		"THREE_D": 1,
		"IMAX":    2,
		"FOUR_D":  3,
	}
)

func (x MovieFormat) Enum() *MovieFormat {
	p := new(MovieFormat)
	*p = x
	return p
}

func (x MovieFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovieFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_producer_service_proto_enumTypes[1].Descriptor()
}

func (MovieFormat) Type() protoreflect.EnumType {
	return &file_producer_service_proto_enumTypes[1]
}

func (x MovieFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovieFormat.Descriptor instead.
func (MovieFormat) EnumDescriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{1}
}

type Payment struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	Billing                  *Payment_Billing           `protobuf:"bytes,1,opt,name=billing,proto3" json:"billing,omitempty"`
	BrandId                  string                     `protobuf:"bytes,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BusinessId               string                     `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CardIssuingCountry       string                     `protobuf:"bytes,4,opt,name=card_issuing_country,json=cardIssuingCountry,proto3" json:"card_issuing_country,omitempty"`
	CardLastFour             string                     `protobuf:"bytes,5,opt,name=card_last_four,json=cardLastFour,proto3" json:"card_last_four,omitempty"`
	CardNetwork              string                     `protobuf:"bytes,6,opt,name=card_network,json=cardNetwork,proto3" json:"card_network,omitempty"`
	CardType                 string                     `protobuf:"bytes,7,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CreatedAt                *timestamp.Timestamp       `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Currency                 string                     `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Customer                 *Payment_Customer          `protobuf:"bytes,10,opt,name=customer,proto3" json:"customer,omitempty"`
	DigitalProductsDelivered bool                       `protobuf:"varint,11,opt,name=digital_products_delivered,json=digitalProductsDelivered,proto3" json:"digital_products_delivered,omitempty"`
	DiscountId               string                     `protobuf:"bytes,12,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"`
	Disputes                 []*Payment_Dispute         `protobuf:"bytes,13,rep,name=disputes,proto3" json:"disputes,omitempty"`
	ErrorCode                string                     `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage             string                     `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Metadata                 map[string]string          `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Assumes flattened key/value strings
	PaymentId                string                     `protobuf:"bytes,17,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentLink              string                     `protobuf:"bytes,18,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	PaymentMethod            string                     `protobuf:"bytes,19,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentMethodType        string                     `protobuf:"bytes,20,opt,name=payment_method_type,json=paymentMethodType,proto3" json:"payment_method_type,omitempty"`
	ProductCart              []*Payment_ProductCartItem `protobuf:"bytes,21,rep,name=product_cart,json=productCart,proto3" json:"product_cart,omitempty"`
	Refunds                  []*Payment_Refund          `protobuf:"bytes,22,rep,name=refunds,proto3" json:"refunds,omitempty"`
	SettlementAmount         int32                      `protobuf:"varint,23,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	SettlementCurrency       string                     `protobuf:"bytes,24,opt,name=settlement_currency,json=settlementCurrency,proto3" json:"settlement_currency,omitempty"`
	SettlementTax            int32                      `protobuf:"varint,25,opt,name=settlement_tax,json=settlementTax,proto3" json:"settlement_tax,omitempty"`
	Status                   string                     `protobuf:"bytes,26,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionId           string                     `protobuf:"bytes,27,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Tax                      int32                      `protobuf:"varint,28,opt,name=tax,proto3" json:"tax,omitempty"`
	TotalAmount              int32                      `protobuf:"varint,29,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	UpdatedAt                *timestamp.Timestamp       `protobuf:"bytes,30,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_producer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetBilling() *Payment_Billing {
	if x != nil {
		return x.Billing
	}
	return nil
}

func (x *Payment) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Payment) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Payment) GetCardIssuingCountry() string {
	if x != nil {
		return x.CardIssuingCountry
	}
	return ""
}

func (x *Payment) GetCardLastFour() string {
	if x != nil {
		return x.CardLastFour
	}
	return ""
}

func (x *Payment) GetCardNetwork() string {
	if x != nil {
		return x.CardNetwork
	}
	return ""
}

func (x *Payment) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetCustomer() *Payment_Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Payment) GetDigitalProductsDelivered() bool {
	if x != nil {
		return x.DigitalProductsDelivered
	}
	return false
}

func (x *Payment) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

func (x *Payment) GetDisputes() []*Payment_Dispute {
	if x != nil {
		return x.Disputes
	}
	return nil
}

func (x *Payment) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Payment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payment) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetPaymentMethodType() string {
	if x != nil {
		return x.PaymentMethodType
	}
	return ""
}

func (x *Payment) GetProductCart() []*Payment_ProductCartItem {
	if x != nil {
		return x.ProductCart
	}
	return nil
}

func (x *Payment) GetRefunds() []*Payment_Refund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

func (x *Payment) GetSettlementAmount() int32 {
	if x != nil {
		return x.SettlementAmount
	}
	return 0
}

func (x *Payment) GetSettlementCurrency() string {
	if x != nil {
		return x.SettlementCurrency
	}
	return ""
}

func (x *Payment) GetSettlementTax() int32 {
	if x != nil {
		return x.SettlementTax
	}
	return 0
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Payment) GetTax() int32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Payment) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Payment) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Payment_Service_Producer_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentPayload *Payment               `protobuf:"bytes,1,opt,name=payment_payload,json=paymentPayload,proto3" json:"payment_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment_Service_Producer_Request) Reset() {
	*x = Payment_Service_Producer_Request{}
	mi := &file_producer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Service_Producer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Service_Producer_Request) ProtoMessage() {}

func (x *Payment_Service_Producer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Service_Producer_Request.ProtoReflect.Descriptor instead.
func (*Payment_Service_Producer_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{1}
}

func (x *Payment_Service_Producer_Request) GetPaymentPayload() *Payment {
	if x != nil {
		return x.PaymentPayload
	}
	return nil
}

type Payment_Service_Producer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Service_Producer_Response) Reset() {
	*x = Payment_Service_Producer_Response{}
	mi := &file_producer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Service_Producer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Service_Producer_Response) ProtoMessage() {}

func (x *Payment_Service_Producer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Service_Producer_Response.ProtoReflect.Descriptor instead.
func (*Payment_Service_Producer_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{2}
}

func (x *Payment_Service_Producer_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Lock_Seats_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []int32                `protobuf:"varint,1,rep,packed,name=seatIds,proto3" json:"seatIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock_Seats_Request) Reset() {
	*x = Lock_Seats_Request{}
	mi := &file_producer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock_Seats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock_Seats_Request) ProtoMessage() {}

func (x *Lock_Seats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock_Seats_Request.ProtoReflect.Descriptor instead.
func (*Lock_Seats_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{3}
}

func (x *Lock_Seats_Request) GetSeatIds() []int32 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type Lock_Seats_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock_Seats_Response) Reset() {
	*x = Lock_Seats_Response{}
	mi := &file_producer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock_Seats_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock_Seats_Response) ProtoMessage() {}

func (x *Lock_Seats_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock_Seats_Response.ProtoReflect.Descriptor instead.
func (*Lock_Seats_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{4}
}

func (x *Lock_Seats_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Unlock_Seats_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []int32                `protobuf:"varint,1,rep,packed,name=seatIds,proto3" json:"seatIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlock_Seats_Request) Reset() {
	*x = Unlock_Seats_Request{}
	mi := &file_producer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlock_Seats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlock_Seats_Request) ProtoMessage() {}

func (x *Unlock_Seats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlock_Seats_Request.ProtoReflect.Descriptor instead.
func (*Unlock_Seats_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{5}
}

func (x *Unlock_Seats_Request) GetSeatIds() []int32 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type Unlock_Seats_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlock_Seats_Response) Reset() {
	*x = Unlock_Seats_Response{}
	mi := &file_producer_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlock_Seats_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlock_Seats_Response) ProtoMessage() {}

func (x *Unlock_Seats_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlock_Seats_Response.ProtoReflect.Descriptor instead.
func (*Unlock_Seats_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{6}
}

func (x *Unlock_Seats_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Send_Mail_Producer_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string email = 1;
	// string phone_number = 2;
	To            string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Text          string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Html          string `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	Category      string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Subject       string `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Send_Mail_Producer_Request) Reset() {
	*x = Send_Mail_Producer_Request{}
	mi := &file_producer_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Send_Mail_Producer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send_Mail_Producer_Request) ProtoMessage() {}

func (x *Send_Mail_Producer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send_Mail_Producer_Request.ProtoReflect.Descriptor instead.
func (*Send_Mail_Producer_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{7}
}

func (x *Send_Mail_Producer_Request) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Send_Mail_Producer_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Send_Mail_Producer_Request) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Send_Mail_Producer_Request) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *Send_Mail_Producer_Request) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Send_Mail_Producer_Request) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type Send_Mail_Producer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Send_Mail_Producer_Response) Reset() {
	*x = Send_Mail_Producer_Response{}
	mi := &file_producer_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Send_Mail_Producer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send_Mail_Producer_Response) ProtoMessage() {}

func (x *Send_Mail_Producer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send_Mail_Producer_Response.ProtoReflect.Descriptor instead.
func (*Send_Mail_Producer_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{8}
}

func (x *Send_Mail_Producer_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Cast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          CastType               `protobuf:"varint,5,opt,name=type,proto3,enum=rabbitmq_producer_service.CastType" json:"type,omitempty"`
	CharacterName string                 `protobuf:"bytes,6,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	MovieId       int32                  `protobuf:"varint,8,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	// int32 starpi_cast_uid = 9;
	CastId           int32  `protobuf:"varint,10,opt,name=cast_id,json=castId,proto3" json:"cast_id,omitempty"`
	StarpiCastUidStr string `protobuf:"bytes,11,opt,name=starpi_cast_uid_str,json=starpiCastUidStr,proto3" json:"starpi_cast_uid_str,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cast) Reset() {
	*x = Cast{}
	mi := &file_producer_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{9}
}

func (x *Cast) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cast) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cast) GetType() CastType {
	if x != nil {
		return x.Type
	}
	return CastType_ACTOR
}

func (x *Cast) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *Cast) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Cast) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *Cast) GetCastId() int32 {
	if x != nil {
		return x.CastId
	}
	return 0
}

func (x *Cast) GetStarpiCastUidStr() string {
	if x != nil {
		return x.StarpiCastUidStr
	}
	return ""
}

type Cast_Service_Producer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cast_Service_Producer_Response) Reset() {
	*x = Cast_Service_Producer_Response{}
	mi := &file_producer_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cast_Service_Producer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast_Service_Producer_Response) ProtoMessage() {}

func (x *Cast_Service_Producer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast_Service_Producer_Response.ProtoReflect.Descriptor instead.
func (*Cast_Service_Producer_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{10}
}

func (x *Cast_Service_Producer_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Cast_Service_Producer_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Movie_Time_Slot_Strapi struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Starttime              string                 `protobuf:"bytes,1,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime                string                 `protobuf:"bytes,2,opt,name=endtime,proto3" json:"endtime,omitempty"`
	Duration               int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Format                 MovieFormat            `protobuf:"varint,4,opt,name=format,proto3,enum=rabbitmq_producer_service.MovieFormat" json:"format,omitempty"`
	MovieId                int32                  `protobuf:"varint,5,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	VenueId                int32                  `protobuf:"varint,6,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Date                   string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	StarpiMovieTimeslotUid string                 `protobuf:"bytes,8,opt,name=starpi_movie_timeslot_uid,json=starpiMovieTimeslotUid,proto3" json:"starpi_movie_timeslot_uid,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Movie_Time_Slot_Strapi) Reset() {
	*x = Movie_Time_Slot_Strapi{}
	mi := &file_producer_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie_Time_Slot_Strapi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie_Time_Slot_Strapi) ProtoMessage() {}

func (x *Movie_Time_Slot_Strapi) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie_Time_Slot_Strapi.ProtoReflect.Descriptor instead.
func (*Movie_Time_Slot_Strapi) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{11}
}

func (x *Movie_Time_Slot_Strapi) GetStarttime() string {
	if x != nil {
		return x.Starttime
	}
	return ""
}

func (x *Movie_Time_Slot_Strapi) GetEndtime() string {
	if x != nil {
		return x.Endtime
	}
	return ""
}

func (x *Movie_Time_Slot_Strapi) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Movie_Time_Slot_Strapi) GetFormat() MovieFormat {
	if x != nil {
		return x.Format
	}
	return MovieFormat_TWO_D
}

func (x *Movie_Time_Slot_Strapi) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *Movie_Time_Slot_Strapi) GetVenueId() int32 {
	if x != nil {
		return x.VenueId
	}
	return 0
}

func (x *Movie_Time_Slot_Strapi) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Movie_Time_Slot_Strapi) GetStarpiMovieTimeslotUid() string {
	if x != nil {
		return x.StarpiMovieTimeslotUid
	}
	return ""
}

type Movie_Time_Slot_Producer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie_Time_Slot_Producer_Response) Reset() {
	*x = Movie_Time_Slot_Producer_Response{}
	mi := &file_producer_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie_Time_Slot_Producer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie_Time_Slot_Producer_Response) ProtoMessage() {}

func (x *Movie_Time_Slot_Producer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie_Time_Slot_Producer_Response.ProtoReflect.Descriptor instead.
func (*Movie_Time_Slot_Producer_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{12}
}

func (x *Movie_Time_Slot_Producer_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Movie_Time_Slot_Producer_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Movie_Strapi struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ReleaseDate      string                 `protobuf:"bytes,3,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Duration         int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Languages        []string               `protobuf:"bytes,5,rep,name=languages,proto3" json:"languages,omitempty"`
	Type             []string               `protobuf:"bytes,6,rep,name=type,proto3" json:"type,omitempty"`
	PosterUrl        string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TrailerUrl       string                 `protobuf:"bytes,8,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	MovieResolution  string                 `protobuf:"bytes,9,opt,name=movie_resolution,json=movieResolution,proto3" json:"movie_resolution,omitempty"`
	Ranking          int32                  `protobuf:"varint,10,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Votes            int32                  `protobuf:"varint,11,opt,name=votes,proto3" json:"votes,omitempty"`
	ScreenWidePoster string                 `protobuf:"bytes,12,opt,name=screenWidePoster,proto3" json:"screenWidePoster,omitempty"`
	LogoPosterURL    string                 `protobuf:"bytes,13,opt,name=logoPosterURL,proto3" json:"logoPosterURL,omitempty"`
	IsSynced         bool                   `protobuf:"varint,14,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	MovieId          int32                  `protobuf:"varint,15,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	StarpiMovieUid   string                 `protobuf:"bytes,16,opt,name=starpi_movie_uid,json=starpiMovieUid,proto3" json:"starpi_movie_uid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Movie_Strapi) Reset() {
	*x = Movie_Strapi{}
	mi := &file_producer_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie_Strapi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie_Strapi) ProtoMessage() {}

func (x *Movie_Strapi) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie_Strapi.ProtoReflect.Descriptor instead.
func (*Movie_Strapi) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{13}
}

func (x *Movie_Strapi) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie_Strapi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie_Strapi) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Movie_Strapi) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Movie_Strapi) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Movie_Strapi) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Movie_Strapi) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Movie_Strapi) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *Movie_Strapi) GetMovieResolution() string {
	if x != nil {
		return x.MovieResolution
	}
	return ""
}

func (x *Movie_Strapi) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *Movie_Strapi) GetVotes() int32 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *Movie_Strapi) GetScreenWidePoster() string {
	if x != nil {
		return x.ScreenWidePoster
	}
	return ""
}

func (x *Movie_Strapi) GetLogoPosterURL() string {
	if x != nil {
		return x.LogoPosterURL
	}
	return ""
}

func (x *Movie_Strapi) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

func (x *Movie_Strapi) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *Movie_Strapi) GetStarpiMovieUid() string {
	if x != nil {
		return x.StarpiMovieUid
	}
	return ""
}

type Venue_Strapi struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Venueid              int32                  `protobuf:"varint,1,opt,name=venueid,proto3" json:"venueid,omitempty"`
	IsSynced             bool                   `protobuf:"varint,2,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Address              string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Rows                 int32                  `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns              int32                  `protobuf:"varint,7,opt,name=columns,proto3" json:"columns,omitempty"`
	ScreenNumber         string                 `protobuf:"bytes,8,opt,name=screen_number,json=screenNumber,proto3" json:"screen_number,omitempty"`
	Longitude            int32                  `protobuf:"varint,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             int32                  `protobuf:"varint,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Movieformatsupported []string               `protobuf:"bytes,11,rep,name=movieformatsupported,proto3" json:"movieformatsupported,omitempty"`
	Languagessupported   []string               `protobuf:"bytes,12,rep,name=languagessupported,proto3" json:"languagessupported,omitempty"`
	Cinemaname           string                 `protobuf:"bytes,13,opt,name=cinemaname,proto3" json:"cinemaname,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Venue_Strapi) Reset() {
	*x = Venue_Strapi{}
	mi := &file_producer_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Venue_Strapi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue_Strapi) ProtoMessage() {}

func (x *Venue_Strapi) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue_Strapi.ProtoReflect.Descriptor instead.
func (*Venue_Strapi) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{14}
}

func (x *Venue_Strapi) GetVenueid() int32 {
	if x != nil {
		return x.Venueid
	}
	return 0
}

func (x *Venue_Strapi) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

func (x *Venue_Strapi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Venue_Strapi) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Venue_Strapi) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Venue_Strapi) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Venue_Strapi) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Venue_Strapi) GetScreenNumber() string {
	if x != nil {
		return x.ScreenNumber
	}
	return ""
}

func (x *Venue_Strapi) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Venue_Strapi) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Venue_Strapi) GetMovieformatsupported() []string {
	if x != nil {
		return x.Movieformatsupported
	}
	return nil
}

func (x *Venue_Strapi) GetLanguagessupported() []string {
	if x != nil {
		return x.Languagessupported
	}
	return nil
}

func (x *Venue_Strapi) GetCinemaname() string {
	if x != nil {
		return x.Cinemaname
	}
	return ""
}

type Payment_Billing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Zipcode       string                 `protobuf:"bytes,5,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Billing) Reset() {
	*x = Payment_Billing{}
	mi := &file_producer_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Billing) ProtoMessage() {}

func (x *Payment_Billing) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Billing.ProtoReflect.Descriptor instead.
func (*Payment_Billing) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Payment_Billing) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Payment_Billing) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Payment_Billing) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Payment_Billing) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Payment_Billing) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

type Payment_Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Customer) Reset() {
	*x = Payment_Customer{}
	mi := &file_producer_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Customer) ProtoMessage() {}

func (x *Payment_Customer) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Customer.ProtoReflect.Descriptor instead.
func (*Payment_Customer) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Payment_Customer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Payment_Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Payment_Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Payment_Dispute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	DisputeId     string                 `protobuf:"bytes,5,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	DisputeStage  string                 `protobuf:"bytes,6,opt,name=dispute_stage,json=disputeStage,proto3" json:"dispute_stage,omitempty"`
	DisputeStatus string                 `protobuf:"bytes,7,opt,name=dispute_status,json=disputeStatus,proto3" json:"dispute_status,omitempty"`
	PaymentId     string                 `protobuf:"bytes,8,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Remarks       string                 `protobuf:"bytes,9,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Dispute) Reset() {
	*x = Payment_Dispute{}
	mi := &file_producer_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Dispute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Dispute) ProtoMessage() {}

func (x *Payment_Dispute) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Dispute.ProtoReflect.Descriptor instead.
func (*Payment_Dispute) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Payment_Dispute) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment_Dispute) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Payment_Dispute) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment_Dispute) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment_Dispute) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

func (x *Payment_Dispute) GetDisputeStage() string {
	if x != nil {
		return x.DisputeStage
	}
	return ""
}

func (x *Payment_Dispute) GetDisputeStatus() string {
	if x != nil {
		return x.DisputeStatus
	}
	return ""
}

func (x *Payment_Dispute) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment_Dispute) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type Payment_ProductCartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_ProductCartItem) Reset() {
	*x = Payment_ProductCartItem{}
	mi := &file_producer_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_ProductCartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_ProductCartItem) ProtoMessage() {}

func (x *Payment_ProductCartItem) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_ProductCartItem.ProtoReflect.Descriptor instead.
func (*Payment_ProductCartItem) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Payment_ProductCartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Payment_ProductCartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Payment_Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IsPartial     bool                   `protobuf:"varint,5,opt,name=is_partial,json=isPartial,proto3" json:"is_partial,omitempty"`
	PaymentId     string                 `protobuf:"bytes,6,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	RefundId      string                 `protobuf:"bytes,8,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Refund) Reset() {
	*x = Payment_Refund{}
	mi := &file_producer_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Refund) ProtoMessage() {}

func (x *Payment_Refund) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Refund.ProtoReflect.Descriptor instead.
func (*Payment_Refund) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Payment_Refund) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment_Refund) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Payment_Refund) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment_Refund) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment_Refund) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

func (x *Payment_Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment_Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Payment_Refund) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *Payment_Refund) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_producer_service_proto protoreflect.FileDescriptor

const file_producer_service_proto_rawDesc = "" +
	"\n" +
	"\x16producer_service.proto\x12\x19rabbitmq_producer_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x12\n" +
	"\aPayment\x12D\n" +
	"\abilling\x18\x01 \x01(\v2*.rabbitmq_producer_service.Payment.BillingR\abilling\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\tR\abrandId\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\x120\n" +
	"\x14card_issuing_country\x18\x04 \x01(\tR\x12cardIssuingCountry\x12$\n" +
	"\x0ecard_last_four\x18\x05 \x01(\tR\fcardLastFour\x12!\n" +
	"\fcard_network\x18\x06 \x01(\tR\vcardNetwork\x12\x1b\n" +
	"\tcard_type\x18\a \x01(\tR\bcardType\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12G\n" +
	"\bcustomer\x18\n" +
	" \x01(\v2+.rabbitmq_producer_service.Payment.CustomerR\bcustomer\x12<\n" +
	"\x1adigital_products_delivered\x18\v \x01(\bR\x18digitalProductsDelivered\x12\x1f\n" +
	"\vdiscount_id\x18\f \x01(\tR\n" +
	"discountId\x12F\n" +
	"\bdisputes\x18\r \x03(\v2*.rabbitmq_producer_service.Payment.DisputeR\bdisputes\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x0f \x01(\tR\ferrorMessage\x12L\n" +
	"\bmetadata\x18\x10 \x03(\v20.rabbitmq_producer_service.Payment.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x11 \x01(\tR\tpaymentId\x12!\n" +
	"\fpayment_link\x18\x12 \x01(\tR\vpaymentLink\x12%\n" +
	"\x0epayment_method\x18\x13 \x01(\tR\rpaymentMethod\x12.\n" +
	"\x13payment_method_type\x18\x14 \x01(\tR\x11paymentMethodType\x12U\n" +
	"\fproduct_cart\x18\x15 \x03(\v22.rabbitmq_producer_service.Payment.ProductCartItemR\vproductCart\x12C\n" +
	"\arefunds\x18\x16 \x03(\v2).rabbitmq_producer_service.Payment.RefundR\arefunds\x12+\n" +
	"\x11settlement_amount\x18\x17 \x01(\x05R\x10settlementAmount\x12/\n" +
	"\x13settlement_currency\x18\x18 \x01(\tR\x12settlementCurrency\x12%\n" +
	"\x0esettlement_tax\x18\x19 \x01(\x05R\rsettlementTax\x12\x16\n" +
	"\x06status\x18\x1a \x01(\tR\x06status\x12'\n" +
	"\x0fsubscription_id\x18\x1b \x01(\tR\x0esubscriptionId\x12\x10\n" +
	"\x03tax\x18\x1c \x01(\x05R\x03tax\x12!\n" +
	"\ftotal_amount\x18\x1d \x01(\x05R\vtotalAmount\x129\n" +
	"\n" +
	"updated_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a\x7f\n" +
	"\aBilling\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x18\n" +
	"\azipcode\x18\x05 \x01(\tR\azipcode\x1aU\n" +
	"\bCustomer\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x1a\xbd\x02\n" +
	"\aDispute\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x05 \x01(\tR\tdisputeId\x12#\n" +
	"\rdispute_stage\x18\x06 \x01(\tR\fdisputeStage\x12%\n" +
	"\x0edispute_status\x18\a \x01(\tR\rdisputeStatus\x12\x1d\n" +
	"\n" +
	"payment_id\x18\b \x01(\tR\tpaymentId\x12\x18\n" +
	"\aremarks\x18\t \x01(\tR\aremarks\x1aL\n" +
	"\x0fProductCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x1a\xa3\x02\n" +
	"\x06Refund\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"is_partial\x18\x05 \x01(\bR\tisPartial\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x06 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1b\n" +
	"\trefund_id\x18\b \x01(\tR\brefundId\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	" Payment_Service_Producer_Request\x12K\n" +
	"\x0fpayment_payload\x18\x01 \x01(\v2\".rabbitmq_producer_service.PaymentR\x0epaymentPayload\"9\n" +
	"!Payment_Service_Producer_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x12Lock_Seats_Request\x12\x18\n" +
	"\aseatIds\x18\x01 \x03(\x05R\aseatIds\"+\n" +
	"\x13Lock_Seats_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"0\n" +
	"\x14Unlock_Seats_Request\x12\x18\n" +
	"\aseatIds\x18\x01 \x03(\x05R\aseatIds\"-\n" +
	"\x15Unlock_Seats_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xaa\x01\n" +
	"\x1aSend_Mail_Producer_Request\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\x06 \x01(\tR\x04html\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubjectJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"3\n" +
	"\x1bSend_Mail_Producer_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xae\x02\n" +
	"\x04Cast\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\x04type\x18\x05 \x01(\x0e2#.rabbitmq_producer_service.CastTypeR\x04type\x12%\n" +
	"\x0echaracter_name\x18\x06 \x01(\tR\rcharacterName\x12\x1b\n" +
	"\tphoto_url\x18\a \x01(\tR\bphotoUrl\x12\x19\n" +
	"\bmovie_id\x18\b \x01(\x05R\amovieId\x12\x17\n" +
	"\acast_id\x18\n" +
	" \x01(\x05R\x06castId\x12-\n" +
	"\x13starpi_cast_uid_str\x18\v \x01(\tR\x10starpiCastUidStrJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\t\x10\n" +
	"\"P\n" +
	"\x1eCast_Service_Producer_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb1\x02\n" +
	"\x16Movie_Time_Slot_Strapi\x12\x1c\n" +
	"\tstarttime\x18\x01 \x01(\tR\tstarttime\x12\x18\n" +
	"\aendtime\x18\x02 \x01(\tR\aendtime\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12>\n" +
	"\x06format\x18\x04 \x01(\x0e2&.rabbitmq_producer_service.MovieFormatR\x06format\x12\x19\n" +
	"\bmovie_id\x18\x05 \x01(\x05R\amovieId\x12\x19\n" +
	"\bvenue_id\x18\x06 \x01(\x05R\avenueId\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x129\n" +
	"\x19starpi_movie_timeslot_uid\x18\b \x01(\tR\x16starpiMovieTimeslotUid\"S\n" +
	"!Movie_Time_Slot_Producer_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x04\n" +
	"\fMovie_Strapi\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\frelease_date\x18\x03 \x01(\tR\vreleaseDate\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1c\n" +
	"\tlanguages\x18\x05 \x03(\tR\tlanguages\x12\x12\n" +
	"\x04type\x18\x06 \x03(\tR\x04type\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vtrailer_url\x18\b \x01(\tR\n" +
	"trailerUrl\x12)\n" +
	"\x10movie_resolution\x18\t \x01(\tR\x0fmovieResolution\x12\x18\n" +
	"\aranking\x18\n" +
	" \x01(\x05R\aranking\x12\x14\n" +
	"\x05votes\x18\v \x01(\x05R\x05votes\x12*\n" +
	"\x10screenWidePoster\x18\f \x01(\tR\x10screenWidePoster\x12$\n" +
	"\rlogoPosterURL\x18\r \x01(\tR\rlogoPosterURL\x12\x1b\n" +
	"\tis_synced\x18\x0e \x01(\bR\bisSynced\x12\x19\n" +
	"\bmovie_id\x18\x0f \x01(\x05R\amovieId\x12(\n" +
	"\x10starpi_movie_uid\x18\x10 \x01(\tR\x0estarpiMovieUid\"\x98\x03\n" +
	"\fVenue_Strapi\x12\x18\n" +
	"\avenueid\x18\x01 \x01(\x05R\avenueid\x12\x1b\n" +
	"\tis_synced\x18\x02 \x01(\bR\bisSynced\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\a \x01(\x05R\acolumns\x12#\n" +
	"\rscreen_number\x18\b \x01(\tR\fscreenNumber\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x05R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x05R\blatitude\x122\n" +
	"\x14movieformatsupported\x18\v \x03(\tR\x14movieformatsupported\x12.\n" +
	"\x12languagessupported\x18\f \x03(\tR\x12languagessupported\x12\x1e\n" +
	"\n" +
	"cinemaname\x18\r \x01(\tR\n" +
	"cinemaname*l\n" +
	"\bCastType\x12\t\n" +
	"\x05ACTOR\x10\x00\x12\f\n" +
	"\bDIRECTOR\x10\x01\x12\f\n" +
	"\bPRODUCER\x10\x02\x12\n" +
	"\n" +
	"\x06WRITER\x10\x03\x12\x13\n" +
	"\x0fCINEMATOGRAPHER\x10\x04\x12\n" +
	"\n" +
	"\x06EDITOR\x10\x05\x12\f\n" +
	"\bCOMPOSER\x10\x06*;\n" +
	"\vMovieFormat\x12\t\n" +
	"\x05TWO_D\x10\x00\x12\v\n" +
	"\aTHREE_D\x10\x01\x12\b\n" +
	"\x04IMAX\x10\x02\x12\n" +
	"\n" +
	"\x06FOUR_D\x10\x032\xa8\v\n" +
	"\x17rabbitmqProducerService\x12\x9d\x01\n" +
	" Payment_Service_Webhook_Producer\x12;.rabbitmq_producer_service.Payment_Service_Producer_Request\x1a<.rabbitmq_producer_service.Payment_Service_Producer_Response\x12k\n" +
	"\n" +
	"Lock_Seats\x12-.rabbitmq_producer_service.Lock_Seats_Request\x1a..rabbitmq_producer_service.Lock_Seats_Response\x12q\n" +
	"\fUnlock_Seats\x12/.rabbitmq_producer_service.Unlock_Seats_Request\x1a0.rabbitmq_producer_service.Unlock_Seats_Response\x12\x83\x01\n" +
	"\x12Send_Mail_Producer\x125.rabbitmq_producer_service.Send_Mail_Producer_Request\x1a6.rabbitmq_producer_service.Send_Mail_Producer_Response\x12\x9d\x01\n" +
	" Payment_Service_Failure_Producer\x12;.rabbitmq_producer_service.Payment_Service_Producer_Request\x1a<.rabbitmq_producer_service.Payment_Service_Producer_Response\x12s\n" +
	"\x15Cast_Service_Producer\x12\x1f.rabbitmq_producer_service.Cast\x1a9.rabbitmq_producer_service.Cast_Service_Producer_Response\x12\x8b\x01\n" +
	"\x18Movie_Time_Slot_Producer\x121.rabbitmq_producer_service.Movie_Time_Slot_Strapi\x1a<.rabbitmq_producer_service.Movie_Time_Slot_Producer_Response\x12r\n" +
	"\x14Delete_Cast_Producer\x12\x1f.rabbitmq_producer_service.Cast\x1a9.rabbitmq_producer_service.Cast_Service_Producer_Response\x12w\n" +
	"\x0eMovie_Producer\x12'.rabbitmq_producer_service.Movie_Strapi\x1a<.rabbitmq_producer_service.Movie_Time_Slot_Producer_Response\x12~\n" +
	"\x15Delete_Movie_Producer\x12'.rabbitmq_producer_service.Movie_Strapi\x1a<.rabbitmq_producer_service.Movie_Time_Slot_Producer_Response\x12w\n" +
	"\x0eVenue_Producer\x12'.rabbitmq_producer_service.Venue_Strapi\x1a<.rabbitmq_producer_service.Movie_Time_Slot_Producer_ResponseBRZPgithub.com/kartik7120/rabbitmq_producer_service/cmd/grpcServer;rabbitmq_producerb\x06proto3"

var (
	file_producer_service_proto_rawDescOnce sync.Once
	file_producer_service_proto_rawDescData []byte
)

func file_producer_service_proto_rawDescGZIP() []byte {
	file_producer_service_proto_rawDescOnce.Do(func() {
		file_producer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producer_service_proto_rawDesc), len(file_producer_service_proto_rawDesc)))
	})
	return file_producer_service_proto_rawDescData
}

var file_producer_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_producer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_producer_service_proto_goTypes = []any{
	(CastType)(0),                             // 0: rabbitmq_producer_service.CastType
	(MovieFormat)(0),                          // 1: rabbitmq_producer_service.MovieFormat
	(*Payment)(nil),                           // 2: rabbitmq_producer_service.Payment
	(*Payment_Service_Producer_Request)(nil),  // 3: rabbitmq_producer_service.Payment_Service_Producer_Request
	(*Payment_Service_Producer_Response)(nil), // 4: rabbitmq_producer_service.Payment_Service_Producer_Response
	(*Lock_Seats_Request)(nil),                // 5: rabbitmq_producer_service.Lock_Seats_Request
	(*Lock_Seats_Response)(nil),               // 6: rabbitmq_producer_service.Lock_Seats_Response
	(*Unlock_Seats_Request)(nil),              // 7: rabbitmq_producer_service.Unlock_Seats_Request
	(*Unlock_Seats_Response)(nil),             // 8: rabbitmq_producer_service.Unlock_Seats_Response
	(*Send_Mail_Producer_Request)(nil),        // 9: rabbitmq_producer_service.Send_Mail_Producer_Request
	(*Send_Mail_Producer_Response)(nil),       // 10: rabbitmq_producer_service.Send_Mail_Producer_Response
	(*Cast)(nil),                              // 11: rabbitmq_producer_service.Cast
	(*Cast_Service_Producer_Response)(nil),    // 12: rabbitmq_producer_service.Cast_Service_Producer_Response
	(*Movie_Time_Slot_Strapi)(nil),            // 13: rabbitmq_producer_service.Movie_Time_Slot_Strapi
	(*Movie_Time_Slot_Producer_Response)(nil), // 14: rabbitmq_producer_service.Movie_Time_Slot_Producer_Response
	(*Movie_Strapi)(nil),                      // 15: rabbitmq_producer_service.Movie_Strapi
	(*Venue_Strapi)(nil),                      // 16: rabbitmq_producer_service.Venue_Strapi
	(*Payment_Billing)(nil),                   // 17: rabbitmq_producer_service.Payment.Billing
	(*Payment_Customer)(nil),                  // 18: rabbitmq_producer_service.Payment.Customer
	(*Payment_Dispute)(nil),                   // 19: rabbitmq_producer_service.Payment.Dispute
	(*Payment_ProductCartItem)(nil),           // 20: rabbitmq_producer_service.Payment.ProductCartItem
	(*Payment_Refund)(nil),                    // 21: rabbitmq_producer_service.Payment.Refund
	nil,                                       // 22: rabbitmq_producer_service.Payment.MetadataEntry
	(*timestamp.Timestamp)(nil),               // 23: google.protobuf.Timestamp
}
var file_producer_service_proto_depIdxs = []int32{
	17, // 0: rabbitmq_producer_service.Payment.billing:type_name -> rabbitmq_producer_service.Payment.Billing
	23, // 1: rabbitmq_producer_service.Payment.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: rabbitmq_producer_service.Payment.customer:type_name -> rabbitmq_producer_service.Payment.Customer
	19, // 3: rabbitmq_producer_service.Payment.disputes:type_name -> rabbitmq_producer_service.Payment.Dispute
	22, // 4: rabbitmq_producer_service.Payment.metadata:type_name -> rabbitmq_producer_service.Payment.MetadataEntry
	20, // 5: rabbitmq_producer_service.Payment.product_cart:type_name -> rabbitmq_producer_service.Payment.ProductCartItem
	21, // 6: rabbitmq_producer_service.Payment.refunds:type_name -> rabbitmq_producer_service.Payment.Refund
	23, // 7: rabbitmq_producer_service.Payment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: rabbitmq_producer_service.Payment_Service_Producer_Request.payment_payload:type_name -> rabbitmq_producer_service.Payment
	0,  // 9: rabbitmq_producer_service.Cast.type:type_name -> rabbitmq_producer_service.CastType
	1,  // 10: rabbitmq_producer_service.Movie_Time_Slot_Strapi.format:type_name -> rabbitmq_producer_service.MovieFormat
	23, // 11: rabbitmq_producer_service.Payment.Dispute.created_at:type_name -> google.protobuf.Timestamp
	23, // 12: rabbitmq_producer_service.Payment.Refund.created_at:type_name -> google.protobuf.Timestamp
	3,  // 13: rabbitmq_producer_service.rabbitmqProducerService.Payment_Service_Webhook_Producer:input_type -> rabbitmq_producer_service.Payment_Service_Producer_Request
	5,  // 14: rabbitmq_producer_service.rabbitmqProducerService.Lock_Seats:input_type -> rabbitmq_producer_service.Lock_Seats_Request
	7,  // 15: rabbitmq_producer_service.rabbitmqProducerService.Unlock_Seats:input_type -> rabbitmq_producer_service.Unlock_Seats_Request
	9,  // 16: rabbitmq_producer_service.rabbitmqProducerService.Send_Mail_Producer:input_type -> rabbitmq_producer_service.Send_Mail_Producer_Request
	3,  // 17: rabbitmq_producer_service.rabbitmqProducerService.Payment_Service_Failure_Producer:input_type -> rabbitmq_producer_service.Payment_Service_Producer_Request
	11, // 18: rabbitmq_producer_service.rabbitmqProducerService.Cast_Service_Producer:input_type -> rabbitmq_producer_service.Cast
	13, // 19: rabbitmq_producer_service.rabbitmqProducerService.Movie_Time_Slot_Producer:input_type -> rabbitmq_producer_service.Movie_Time_Slot_Strapi
	11, // 20: rabbitmq_producer_service.rabbitmqProducerService.Delete_Cast_Producer:input_type -> rabbitmq_producer_service.Cast
	15, // 21: rabbitmq_producer_service.rabbitmqProducerService.Movie_Producer:input_type -> rabbitmq_producer_service.Movie_Strapi
	15, // 22: rabbitmq_producer_service.rabbitmqProducerService.Delete_Movie_Producer:input_type -> rabbitmq_producer_service.Movie_Strapi
	16, // 23: rabbitmq_producer_service.rabbitmqProducerService.Venue_Producer:input_type -> rabbitmq_producer_service.Venue_Strapi
	4,  // 24: rabbitmq_producer_service.rabbitmqProducerService.Payment_Service_Webhook_Producer:output_type -> rabbitmq_producer_service.Payment_Service_Producer_Response
	6,  // 25: rabbitmq_producer_service.rabbitmqProducerService.Lock_Seats:output_type -> rabbitmq_producer_service.Lock_Seats_Response
	8,  // 26: rabbitmq_producer_service.rabbitmqProducerService.Unlock_Seats:output_type -> rabbitmq_producer_service.Unlock_Seats_Response
	10, // 27: rabbitmq_producer_service.rabbitmqProducerService.Send_Mail_Producer:output_type -> rabbitmq_producer_service.Send_Mail_Producer_Response
	4,  // 28: rabbitmq_producer_service.rabbitmqProducerService.Payment_Service_Failure_Producer:output_type -> rabbitmq_producer_service.Payment_Service_Producer_Response
	12, // 29: rabbitmq_producer_service.rabbitmqProducerService.Cast_Service_Producer:output_type -> rabbitmq_producer_service.Cast_Service_Producer_Response
	14, // 30: rabbitmq_producer_service.rabbitmqProducerService.Movie_Time_Slot_Producer:output_type -> rabbitmq_producer_service.Movie_Time_Slot_Producer_Response
	12, // 31: rabbitmq_producer_service.rabbitmqProducerService.Delete_Cast_Producer:output_type -> rabbitmq_producer_service.Cast_Service_Producer_Response
	14, // 32: rabbitmq_producer_service.rabbitmqProducerService.Movie_Producer:output_type -> rabbitmq_producer_service.Movie_Time_Slot_Producer_Response
	14, // 33: rabbitmq_producer_service.rabbitmqProducerService.Delete_Movie_Producer:output_type -> rabbitmq_producer_service.Movie_Time_Slot_Producer_Response
	14, // 34: rabbitmq_producer_service.rabbitmqProducerService.Venue_Producer:output_type -> rabbitmq_producer_service.Movie_Time_Slot_Producer_Response
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_producer_service_proto_init() }
func file_producer_service_proto_init() {
	if File_producer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producer_service_proto_rawDesc), len(file_producer_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producer_service_proto_goTypes,
		DependencyIndexes: file_producer_service_proto_depIdxs,
		EnumInfos:         file_producer_service_proto_enumTypes,
		MessageInfos:      file_producer_service_proto_msgTypes,
	}.Build()
	File_producer_service_proto = out.File
	file_producer_service_proto_goTypes = nil
	file_producer_service_proto_depIdxs = nil
}
