// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: producer_service.proto

package rabbitmq_producer

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	Billing                  *Payment_Billing           `protobuf:"bytes,1,opt,name=billing,proto3" json:"billing,omitempty"`
	BrandId                  string                     `protobuf:"bytes,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BusinessId               string                     `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CardIssuingCountry       string                     `protobuf:"bytes,4,opt,name=card_issuing_country,json=cardIssuingCountry,proto3" json:"card_issuing_country,omitempty"`
	CardLastFour             string                     `protobuf:"bytes,5,opt,name=card_last_four,json=cardLastFour,proto3" json:"card_last_four,omitempty"`
	CardNetwork              string                     `protobuf:"bytes,6,opt,name=card_network,json=cardNetwork,proto3" json:"card_network,omitempty"`
	CardType                 string                     `protobuf:"bytes,7,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CreatedAt                *timestamp.Timestamp       `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Currency                 string                     `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Customer                 *Payment_Customer          `protobuf:"bytes,10,opt,name=customer,proto3" json:"customer,omitempty"`
	DigitalProductsDelivered bool                       `protobuf:"varint,11,opt,name=digital_products_delivered,json=digitalProductsDelivered,proto3" json:"digital_products_delivered,omitempty"`
	DiscountId               string                     `protobuf:"bytes,12,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"`
	Disputes                 []*Payment_Dispute         `protobuf:"bytes,13,rep,name=disputes,proto3" json:"disputes,omitempty"`
	ErrorCode                string                     `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage             string                     `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Metadata                 map[string]string          `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Assumes flattened key/value strings
	PaymentId                string                     `protobuf:"bytes,17,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentLink              string                     `protobuf:"bytes,18,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	PaymentMethod            string                     `protobuf:"bytes,19,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentMethodType        string                     `protobuf:"bytes,20,opt,name=payment_method_type,json=paymentMethodType,proto3" json:"payment_method_type,omitempty"`
	ProductCart              []*Payment_ProductCartItem `protobuf:"bytes,21,rep,name=product_cart,json=productCart,proto3" json:"product_cart,omitempty"`
	Refunds                  []*Payment_Refund          `protobuf:"bytes,22,rep,name=refunds,proto3" json:"refunds,omitempty"`
	SettlementAmount         int32                      `protobuf:"varint,23,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	SettlementCurrency       string                     `protobuf:"bytes,24,opt,name=settlement_currency,json=settlementCurrency,proto3" json:"settlement_currency,omitempty"`
	SettlementTax            int32                      `protobuf:"varint,25,opt,name=settlement_tax,json=settlementTax,proto3" json:"settlement_tax,omitempty"`
	Status                   string                     `protobuf:"bytes,26,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionId           string                     `protobuf:"bytes,27,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Tax                      int32                      `protobuf:"varint,28,opt,name=tax,proto3" json:"tax,omitempty"`
	TotalAmount              int32                      `protobuf:"varint,29,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	UpdatedAt                *timestamp.Timestamp       `protobuf:"bytes,30,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_producer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetBilling() *Payment_Billing {
	if x != nil {
		return x.Billing
	}
	return nil
}

func (x *Payment) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Payment) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Payment) GetCardIssuingCountry() string {
	if x != nil {
		return x.CardIssuingCountry
	}
	return ""
}

func (x *Payment) GetCardLastFour() string {
	if x != nil {
		return x.CardLastFour
	}
	return ""
}

func (x *Payment) GetCardNetwork() string {
	if x != nil {
		return x.CardNetwork
	}
	return ""
}

func (x *Payment) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetCustomer() *Payment_Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Payment) GetDigitalProductsDelivered() bool {
	if x != nil {
		return x.DigitalProductsDelivered
	}
	return false
}

func (x *Payment) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

func (x *Payment) GetDisputes() []*Payment_Dispute {
	if x != nil {
		return x.Disputes
	}
	return nil
}

func (x *Payment) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Payment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payment) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetPaymentMethodType() string {
	if x != nil {
		return x.PaymentMethodType
	}
	return ""
}

func (x *Payment) GetProductCart() []*Payment_ProductCartItem {
	if x != nil {
		return x.ProductCart
	}
	return nil
}

func (x *Payment) GetRefunds() []*Payment_Refund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

func (x *Payment) GetSettlementAmount() int32 {
	if x != nil {
		return x.SettlementAmount
	}
	return 0
}

func (x *Payment) GetSettlementCurrency() string {
	if x != nil {
		return x.SettlementCurrency
	}
	return ""
}

func (x *Payment) GetSettlementTax() int32 {
	if x != nil {
		return x.SettlementTax
	}
	return 0
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Payment) GetTax() int32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Payment) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Payment) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Payment_Service_Producer_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentPayload *Payment               `protobuf:"bytes,1,opt,name=payment_payload,json=paymentPayload,proto3" json:"payment_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment_Service_Producer_Request) Reset() {
	*x = Payment_Service_Producer_Request{}
	mi := &file_producer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Service_Producer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Service_Producer_Request) ProtoMessage() {}

func (x *Payment_Service_Producer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Service_Producer_Request.ProtoReflect.Descriptor instead.
func (*Payment_Service_Producer_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{1}
}

func (x *Payment_Service_Producer_Request) GetPaymentPayload() *Payment {
	if x != nil {
		return x.PaymentPayload
	}
	return nil
}

type Payment_Service_Producer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Service_Producer_Response) Reset() {
	*x = Payment_Service_Producer_Response{}
	mi := &file_producer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Service_Producer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Service_Producer_Response) ProtoMessage() {}

func (x *Payment_Service_Producer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Service_Producer_Response.ProtoReflect.Descriptor instead.
func (*Payment_Service_Producer_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{2}
}

func (x *Payment_Service_Producer_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Lock_Seats_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []int32                `protobuf:"varint,1,rep,packed,name=seatIds,proto3" json:"seatIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock_Seats_Request) Reset() {
	*x = Lock_Seats_Request{}
	mi := &file_producer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock_Seats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock_Seats_Request) ProtoMessage() {}

func (x *Lock_Seats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock_Seats_Request.ProtoReflect.Descriptor instead.
func (*Lock_Seats_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{3}
}

func (x *Lock_Seats_Request) GetSeatIds() []int32 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type Lock_Seats_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock_Seats_Response) Reset() {
	*x = Lock_Seats_Response{}
	mi := &file_producer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock_Seats_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock_Seats_Response) ProtoMessage() {}

func (x *Lock_Seats_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock_Seats_Response.ProtoReflect.Descriptor instead.
func (*Lock_Seats_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{4}
}

func (x *Lock_Seats_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Unlock_Seats_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []int32                `protobuf:"varint,1,rep,packed,name=seatIds,proto3" json:"seatIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlock_Seats_Request) Reset() {
	*x = Unlock_Seats_Request{}
	mi := &file_producer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlock_Seats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlock_Seats_Request) ProtoMessage() {}

func (x *Unlock_Seats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlock_Seats_Request.ProtoReflect.Descriptor instead.
func (*Unlock_Seats_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{5}
}

func (x *Unlock_Seats_Request) GetSeatIds() []int32 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type Unlock_Seats_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlock_Seats_Response) Reset() {
	*x = Unlock_Seats_Response{}
	mi := &file_producer_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlock_Seats_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlock_Seats_Response) ProtoMessage() {}

func (x *Unlock_Seats_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlock_Seats_Response.ProtoReflect.Descriptor instead.
func (*Unlock_Seats_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{6}
}

func (x *Unlock_Seats_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Send_Mail_Producer_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Send_Mail_Producer_Request) Reset() {
	*x = Send_Mail_Producer_Request{}
	mi := &file_producer_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Send_Mail_Producer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send_Mail_Producer_Request) ProtoMessage() {}

func (x *Send_Mail_Producer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send_Mail_Producer_Request.ProtoReflect.Descriptor instead.
func (*Send_Mail_Producer_Request) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{7}
}

func (x *Send_Mail_Producer_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Send_Mail_Producer_Request) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type Send_Mail_Producer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Send_Mail_Producer_Response) Reset() {
	*x = Send_Mail_Producer_Response{}
	mi := &file_producer_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Send_Mail_Producer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send_Mail_Producer_Response) ProtoMessage() {}

func (x *Send_Mail_Producer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send_Mail_Producer_Response.ProtoReflect.Descriptor instead.
func (*Send_Mail_Producer_Response) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{8}
}

func (x *Send_Mail_Producer_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Payment_Billing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Zipcode       string                 `protobuf:"bytes,5,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Billing) Reset() {
	*x = Payment_Billing{}
	mi := &file_producer_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Billing) ProtoMessage() {}

func (x *Payment_Billing) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Billing.ProtoReflect.Descriptor instead.
func (*Payment_Billing) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Payment_Billing) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Payment_Billing) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Payment_Billing) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Payment_Billing) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Payment_Billing) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

type Payment_Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Customer) Reset() {
	*x = Payment_Customer{}
	mi := &file_producer_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Customer) ProtoMessage() {}

func (x *Payment_Customer) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Customer.ProtoReflect.Descriptor instead.
func (*Payment_Customer) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Payment_Customer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Payment_Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Payment_Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Payment_Dispute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	DisputeId     string                 `protobuf:"bytes,5,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	DisputeStage  string                 `protobuf:"bytes,6,opt,name=dispute_stage,json=disputeStage,proto3" json:"dispute_stage,omitempty"`
	DisputeStatus string                 `protobuf:"bytes,7,opt,name=dispute_status,json=disputeStatus,proto3" json:"dispute_status,omitempty"`
	PaymentId     string                 `protobuf:"bytes,8,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Remarks       string                 `protobuf:"bytes,9,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Dispute) Reset() {
	*x = Payment_Dispute{}
	mi := &file_producer_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Dispute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Dispute) ProtoMessage() {}

func (x *Payment_Dispute) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Dispute.ProtoReflect.Descriptor instead.
func (*Payment_Dispute) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Payment_Dispute) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment_Dispute) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Payment_Dispute) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment_Dispute) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment_Dispute) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

func (x *Payment_Dispute) GetDisputeStage() string {
	if x != nil {
		return x.DisputeStage
	}
	return ""
}

func (x *Payment_Dispute) GetDisputeStatus() string {
	if x != nil {
		return x.DisputeStatus
	}
	return ""
}

func (x *Payment_Dispute) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment_Dispute) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type Payment_ProductCartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_ProductCartItem) Reset() {
	*x = Payment_ProductCartItem{}
	mi := &file_producer_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_ProductCartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_ProductCartItem) ProtoMessage() {}

func (x *Payment_ProductCartItem) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_ProductCartItem.ProtoReflect.Descriptor instead.
func (*Payment_ProductCartItem) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Payment_ProductCartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Payment_ProductCartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Payment_Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IsPartial     bool                   `protobuf:"varint,5,opt,name=is_partial,json=isPartial,proto3" json:"is_partial,omitempty"`
	PaymentId     string                 `protobuf:"bytes,6,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	RefundId      string                 `protobuf:"bytes,8,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Refund) Reset() {
	*x = Payment_Refund{}
	mi := &file_producer_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Refund) ProtoMessage() {}

func (x *Payment_Refund) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Refund.ProtoReflect.Descriptor instead.
func (*Payment_Refund) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Payment_Refund) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment_Refund) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Payment_Refund) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment_Refund) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment_Refund) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

func (x *Payment_Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment_Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Payment_Refund) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *Payment_Refund) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_producer_service_proto protoreflect.FileDescriptor

const file_producer_service_proto_rawDesc = "" +
	"\n" +
	"\x16producer_service.proto\x12\x19rabbitmq_producer_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x12\n" +
	"\aPayment\x12D\n" +
	"\abilling\x18\x01 \x01(\v2*.rabbitmq_producer_service.Payment.BillingR\abilling\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\tR\abrandId\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\x120\n" +
	"\x14card_issuing_country\x18\x04 \x01(\tR\x12cardIssuingCountry\x12$\n" +
	"\x0ecard_last_four\x18\x05 \x01(\tR\fcardLastFour\x12!\n" +
	"\fcard_network\x18\x06 \x01(\tR\vcardNetwork\x12\x1b\n" +
	"\tcard_type\x18\a \x01(\tR\bcardType\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12G\n" +
	"\bcustomer\x18\n" +
	" \x01(\v2+.rabbitmq_producer_service.Payment.CustomerR\bcustomer\x12<\n" +
	"\x1adigital_products_delivered\x18\v \x01(\bR\x18digitalProductsDelivered\x12\x1f\n" +
	"\vdiscount_id\x18\f \x01(\tR\n" +
	"discountId\x12F\n" +
	"\bdisputes\x18\r \x03(\v2*.rabbitmq_producer_service.Payment.DisputeR\bdisputes\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x0f \x01(\tR\ferrorMessage\x12L\n" +
	"\bmetadata\x18\x10 \x03(\v20.rabbitmq_producer_service.Payment.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x11 \x01(\tR\tpaymentId\x12!\n" +
	"\fpayment_link\x18\x12 \x01(\tR\vpaymentLink\x12%\n" +
	"\x0epayment_method\x18\x13 \x01(\tR\rpaymentMethod\x12.\n" +
	"\x13payment_method_type\x18\x14 \x01(\tR\x11paymentMethodType\x12U\n" +
	"\fproduct_cart\x18\x15 \x03(\v22.rabbitmq_producer_service.Payment.ProductCartItemR\vproductCart\x12C\n" +
	"\arefunds\x18\x16 \x03(\v2).rabbitmq_producer_service.Payment.RefundR\arefunds\x12+\n" +
	"\x11settlement_amount\x18\x17 \x01(\x05R\x10settlementAmount\x12/\n" +
	"\x13settlement_currency\x18\x18 \x01(\tR\x12settlementCurrency\x12%\n" +
	"\x0esettlement_tax\x18\x19 \x01(\x05R\rsettlementTax\x12\x16\n" +
	"\x06status\x18\x1a \x01(\tR\x06status\x12'\n" +
	"\x0fsubscription_id\x18\x1b \x01(\tR\x0esubscriptionId\x12\x10\n" +
	"\x03tax\x18\x1c \x01(\x05R\x03tax\x12!\n" +
	"\ftotal_amount\x18\x1d \x01(\x05R\vtotalAmount\x129\n" +
	"\n" +
	"updated_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a\x7f\n" +
	"\aBilling\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x18\n" +
	"\azipcode\x18\x05 \x01(\tR\azipcode\x1aU\n" +
	"\bCustomer\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x1a\xbd\x02\n" +
	"\aDispute\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x05 \x01(\tR\tdisputeId\x12#\n" +
	"\rdispute_stage\x18\x06 \x01(\tR\fdisputeStage\x12%\n" +
	"\x0edispute_status\x18\a \x01(\tR\rdisputeStatus\x12\x1d\n" +
	"\n" +
	"payment_id\x18\b \x01(\tR\tpaymentId\x12\x18\n" +
	"\aremarks\x18\t \x01(\tR\aremarks\x1aL\n" +
	"\x0fProductCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x1a\xa3\x02\n" +
	"\x06Refund\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"is_partial\x18\x05 \x01(\bR\tisPartial\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x06 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1b\n" +
	"\trefund_id\x18\b \x01(\tR\brefundId\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	" Payment_Service_Producer_Request\x12K\n" +
	"\x0fpayment_payload\x18\x01 \x01(\v2\".rabbitmq_producer_service.PaymentR\x0epaymentPayload\"9\n" +
	"!Payment_Service_Producer_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x12Lock_Seats_Request\x12\x18\n" +
	"\aseatIds\x18\x01 \x03(\x05R\aseatIds\"+\n" +
	"\x13Lock_Seats_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"0\n" +
	"\x14Unlock_Seats_Request\x12\x18\n" +
	"\aseatIds\x18\x01 \x03(\x05R\aseatIds\"-\n" +
	"\x15Unlock_Seats_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"U\n" +
	"\x1aSend_Mail_Producer_Request\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\"3\n" +
	"\x1bSend_Mail_Producer_Response\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x9f\x04\n" +
	"\x17rabbitmqProducerService\x12\x9d\x01\n" +
	" Payment_Service_Webhook_Producer\x12;.rabbitmq_producer_service.Payment_Service_Producer_Request\x1a<.rabbitmq_producer_service.Payment_Service_Producer_Response\x12k\n" +
	"\n" +
	"Lock_Seats\x12-.rabbitmq_producer_service.Lock_Seats_Request\x1a..rabbitmq_producer_service.Lock_Seats_Response\x12q\n" +
	"\fUnlock_Seats\x12/.rabbitmq_producer_service.Unlock_Seats_Request\x1a0.rabbitmq_producer_service.Unlock_Seats_Response\x12\x83\x01\n" +
	"\x12Send_Mail_Producer\x125.rabbitmq_producer_service.Send_Mail_Producer_Request\x1a6.rabbitmq_producer_service.Send_Mail_Producer_ResponseBRZPgithub.com/kartik7120/rabbitmq_producer_service/cmd/grpcServer;rabbitmq_producerb\x06proto3"

var (
	file_producer_service_proto_rawDescOnce sync.Once
	file_producer_service_proto_rawDescData []byte
)

func file_producer_service_proto_rawDescGZIP() []byte {
	file_producer_service_proto_rawDescOnce.Do(func() {
		file_producer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producer_service_proto_rawDesc), len(file_producer_service_proto_rawDesc)))
	})
	return file_producer_service_proto_rawDescData
}

var file_producer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_producer_service_proto_goTypes = []any{
	(*Payment)(nil),                           // 0: rabbitmq_producer_service.Payment
	(*Payment_Service_Producer_Request)(nil),  // 1: rabbitmq_producer_service.Payment_Service_Producer_Request
	(*Payment_Service_Producer_Response)(nil), // 2: rabbitmq_producer_service.Payment_Service_Producer_Response
	(*Lock_Seats_Request)(nil),                // 3: rabbitmq_producer_service.Lock_Seats_Request
	(*Lock_Seats_Response)(nil),               // 4: rabbitmq_producer_service.Lock_Seats_Response
	(*Unlock_Seats_Request)(nil),              // 5: rabbitmq_producer_service.Unlock_Seats_Request
	(*Unlock_Seats_Response)(nil),             // 6: rabbitmq_producer_service.Unlock_Seats_Response
	(*Send_Mail_Producer_Request)(nil),        // 7: rabbitmq_producer_service.Send_Mail_Producer_Request
	(*Send_Mail_Producer_Response)(nil),       // 8: rabbitmq_producer_service.Send_Mail_Producer_Response
	(*Payment_Billing)(nil),                   // 9: rabbitmq_producer_service.Payment.Billing
	(*Payment_Customer)(nil),                  // 10: rabbitmq_producer_service.Payment.Customer
	(*Payment_Dispute)(nil),                   // 11: rabbitmq_producer_service.Payment.Dispute
	(*Payment_ProductCartItem)(nil),           // 12: rabbitmq_producer_service.Payment.ProductCartItem
	(*Payment_Refund)(nil),                    // 13: rabbitmq_producer_service.Payment.Refund
	nil,                                       // 14: rabbitmq_producer_service.Payment.MetadataEntry
	(*timestamp.Timestamp)(nil),               // 15: google.protobuf.Timestamp
}
var file_producer_service_proto_depIdxs = []int32{
	9,  // 0: rabbitmq_producer_service.Payment.billing:type_name -> rabbitmq_producer_service.Payment.Billing
	15, // 1: rabbitmq_producer_service.Payment.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: rabbitmq_producer_service.Payment.customer:type_name -> rabbitmq_producer_service.Payment.Customer
	11, // 3: rabbitmq_producer_service.Payment.disputes:type_name -> rabbitmq_producer_service.Payment.Dispute
	14, // 4: rabbitmq_producer_service.Payment.metadata:type_name -> rabbitmq_producer_service.Payment.MetadataEntry
	12, // 5: rabbitmq_producer_service.Payment.product_cart:type_name -> rabbitmq_producer_service.Payment.ProductCartItem
	13, // 6: rabbitmq_producer_service.Payment.refunds:type_name -> rabbitmq_producer_service.Payment.Refund
	15, // 7: rabbitmq_producer_service.Payment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: rabbitmq_producer_service.Payment_Service_Producer_Request.payment_payload:type_name -> rabbitmq_producer_service.Payment
	15, // 9: rabbitmq_producer_service.Payment.Dispute.created_at:type_name -> google.protobuf.Timestamp
	15, // 10: rabbitmq_producer_service.Payment.Refund.created_at:type_name -> google.protobuf.Timestamp
	1,  // 11: rabbitmq_producer_service.rabbitmqProducerService.Payment_Service_Webhook_Producer:input_type -> rabbitmq_producer_service.Payment_Service_Producer_Request
	3,  // 12: rabbitmq_producer_service.rabbitmqProducerService.Lock_Seats:input_type -> rabbitmq_producer_service.Lock_Seats_Request
	5,  // 13: rabbitmq_producer_service.rabbitmqProducerService.Unlock_Seats:input_type -> rabbitmq_producer_service.Unlock_Seats_Request
	7,  // 14: rabbitmq_producer_service.rabbitmqProducerService.Send_Mail_Producer:input_type -> rabbitmq_producer_service.Send_Mail_Producer_Request
	2,  // 15: rabbitmq_producer_service.rabbitmqProducerService.Payment_Service_Webhook_Producer:output_type -> rabbitmq_producer_service.Payment_Service_Producer_Response
	4,  // 16: rabbitmq_producer_service.rabbitmqProducerService.Lock_Seats:output_type -> rabbitmq_producer_service.Lock_Seats_Response
	6,  // 17: rabbitmq_producer_service.rabbitmqProducerService.Unlock_Seats:output_type -> rabbitmq_producer_service.Unlock_Seats_Response
	8,  // 18: rabbitmq_producer_service.rabbitmqProducerService.Send_Mail_Producer:output_type -> rabbitmq_producer_service.Send_Mail_Producer_Response
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_producer_service_proto_init() }
func file_producer_service_proto_init() {
	if File_producer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producer_service_proto_rawDesc), len(file_producer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producer_service_proto_goTypes,
		DependencyIndexes: file_producer_service_proto_depIdxs,
		MessageInfos:      file_producer_service_proto_msgTypes,
	}.Build()
	File_producer_service_proto = out.File
	file_producer_service_proto_goTypes = nil
	file_producer_service_proto_depIdxs = nil
}
